### ISSUE TITLE
Private Chat Rooms

### ISSUE THREAD

**Issue by NewsBeyondDetroit** [Pantsoffski/Author-Chat-Plugin#7]
Hi Piotr. We have reinstalled Author-Chat 2.0.3 after having issues with older versions.   The app is working, but I cannot add Private Rooms to the interface, and I don't see the option working where the pop-up chat appears on any page on the site. It is only appearing on the Admin page.  Last time we had this, we had to pay for the "premium version" for these premium features.  But I no longer see that as an option.

**Comment by Pantsoffski** [comment]
Hello, thanks for your comment. Author Chat is no more premium - it's free for all, so all premium functions are now available for all users without activation. Looks like AC plugin is in conflict with some other element on your website, probably with jQuery library. If previous version worked than try to install it again - in new version some of jQuery lines were rewritten, maybe that's why it doesn't work anymore on your website.
